vasp_cpu:
  machine: cpu_hpc
  number_node: 1
  cpu_per_node: 32
  queue_name: batch2
  group_size: 1
  custom_flags:
    - "#SBATCH -t 7-00:00:00"
    - "#SBATCH --export=ALL"
  source_list: ["/public/home/chenhh/software/catmaster_env.sh"]

mace_gpu:
  machine: gpu_server
  number_node: 1
  cpu_per_node: 16
  gpu_per_node: 1
  queue_name: ""
  group_size: 1
  custom_flags: []
