vasp_execute:
  command: "mpirun -n $SLURM_NTASKS vasp_std > vasp_stdout.out 2>&1 ; sync && sleep 10"
  forward_files:
    - "*"
  backward_files:
    - "*"
  task_work_path: "."

mace_relax:
  command: "python -m catmaster.tools.execution.mace_jobs --structure {structure_file} --fmax {fmax} --steps {maxsteps} --model {model}"
  forward_files:
    - "{structure_file}"
  backward_files:
    - opt.*
    - summary.json
  task_work_path: "."

mace_relax_dir:
  command: "python -m catmaster.tools.execution.mace_jobs --input {input_path} --output_root {output_root} --fmax {fmax} --steps {maxsteps} --model {model}"
  forward_files:
    - "input"
  backward_files:
    - "output"
  task_work_path: "."
